defmodule AshBackpex.Filters.Boolean do
  @moduledoc """
  A Boolean filter for AshBackpex that renders checkboxes for true/false filtering.

  This module provides both the UI rendering (via `Backpex.Filters.Boolean`) and
  the Ash.Expr generation (via `AshBackpex.Filters.Filter` behavior) for filtering
  boolean attributes.

  ## Usage

  The Boolean filter is automatically derived for `:boolean` type attributes when
  using `AshBackpex.LiveResource`. You can also use it directly:

      defmodule MyApp.Filters.Published do
        use AshBackpex.Filters.Boolean

        @impl Backpex.Filter
        def label, do: "Published"
      end

  ## Filter Values

  The filter receives values as a list of strings:
  - `["true"]` - Filter for `true` values only
  - `["false"]` - Filter for `false` values only
  - `["true", "false"]` - No filter applied (both selected = show all)
  - `[]` - No filter applied (none selected)

  ## Options

  By default, this filter provides "True" and "False" checkboxes. You can
  customize the options by overriding the `options/1` callback:

      @impl Backpex.Filters.Boolean
      def options(_assigns) do
        [
          %{label: "Published", key: "true", predicate: nil},
          %{label: "Draft", key: "false", predicate: nil}
        ]
      end

  Note: The `predicate` field is not used by AshBackpex (it's for Backpex's
  Ecto-based filtering). The Ash expression is generated by `to_ash_expr/3`.
  """

  @behaviour AshBackpex.Filters.Filter

  defmacro __using__(_opts) do
    quote do
      use Backpex.Filters.Boolean

      @behaviour AshBackpex.Filters.Filter

      @impl Backpex.Filters.Boolean
      def options(_assigns) do
        [
          %{label: "True", key: "true", predicate: nil},
          %{label: "False", key: "false", predicate: nil}
        ]
      end

      @impl AshBackpex.Filters.Filter
      defdelegate to_ash_expr(field, value, assigns), to: AshBackpex.Filters.Boolean

      defoverridable options: 1, to_ash_expr: 3
    end
  end

  @doc """
  Converts a boolean filter value to an Ash.Expr expression.

  ## Parameters

  - `field` - The atom name of the boolean attribute
  - `value` - The filter value (list of strings or single string)
  - `assigns` - The LiveView assigns (unused by this filter)

  ## Returns

  - `Ash.Expr.t()` - When filtering for true or false only
  - `nil` - When no filter should be applied (both selected, none selected, or invalid)

  ## Examples

      iex> Boolean.to_ash_expr(:published, ["true"], %{})
      #Ash.Expr<published == true>

      iex> Boolean.to_ash_expr(:published, ["false"], %{})
      #Ash.Expr<published == false>

      iex> Boolean.to_ash_expr(:published, ["true", "false"], %{})
      nil

      iex> Boolean.to_ash_expr(:published, [], %{})
      nil
  """
  @impl AshBackpex.Filters.Filter
  def to_ash_expr(_field, nil, _assigns), do: nil
  def to_ash_expr(_field, [], _assigns), do: nil

  def to_ash_expr(field, value, _assigns) when is_binary(value) do
    to_ash_expr(field, [value], %{})
  end

  def to_ash_expr(field, values, _assigns) when is_list(values) do
    true_selected? = "true" in values
    false_selected? = "false" in values

    cond do
      true_selected? and false_selected? ->
        # Both selected means show all - no filter
        nil

      true_selected? ->
        require Ash.Expr
        Ash.Expr.expr(^Ash.Expr.ref(field) == true)

      false_selected? ->
        require Ash.Expr
        Ash.Expr.expr(^Ash.Expr.ref(field) == false)

      true ->
        # Neither selected - no filter
        nil
    end
  end

  def to_ash_expr(_field, _value, _assigns), do: nil
end
