defmodule Demo.Repo.Migrations.AddNumberFieldToPost do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add(:rating, :bigint, default: 3)
    end
  end

  def down do
    alter table(:posts) do
      remove(:rating)
    end
  end
end
