defmodule Demo.Repo.Migrations.AddTagsManyToMany do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :description, :text
      add :slug, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    # alter table(:posts) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :tags
    # end
    #
    create table(:post_tags, primary_key: false) do
      add :tag_id, references(:tags, column: :id, name: "post_tags_tag_id_fkey", type: :uuid),
        primary_key: true,
        null: false

      add :post_id, references(:posts, column: :id, name: "post_tags_post_id_fkey", type: :uuid),
        primary_key: true,
        null: false
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `post_tags` table without the `post_tags_post_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:post_tags)

    # alter table(:posts) do
    # This is the `down` migration of the statement:
    #
    #     remove :tags
    #
    #
    # add :tags, {:array, :text}, null: false, default: []
    # end
    #
    drop table(:tags)
  end
end
