defmodule Demo.Repo.Migrations.RichBlogDemo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:authors, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :joined_on, :date
      add :bio, :text
      add :active, :boolean, null: false
      add :role, :text, null: false
      add :email, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:posts) do
      add :slug, :text, null: false, default: "untitled"
      add :excerpt, :text
      add :status, :text, null: false, default: "draft"
      add :tags, {:array, :text}, null: false, default: []
      add :featured, :boolean, null: false, default: false
      add :published_on, :date
      add :author_id, references(:authors, column: :id, name: "posts_author_id_fkey", type: :uuid)
    end

    create table(:comments, primary_key: false) do
      add :author_id,
          references(:authors, column: :id, name: "comments_author_id_fkey", type: :uuid),
          null: false

      add :post_id, references(:posts, column: :id, name: "comments_post_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :approved, :boolean, null: false
      add :sentiment, :text, null: false
      add :body, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:comments, "comments_post_id_fkey")

    drop constraint(:comments, "comments_author_id_fkey")

    drop table(:comments)

    drop constraint(:posts, "posts_author_id_fkey")

    alter table(:posts) do
      remove :author_id
      remove :published_on
      remove :featured
      remove :tags
      remove :status
      remove :excerpt
      remove :slug
    end

    drop table(:authors)
  end
end
