defmodule Demo.Repo.Migrations.TagTypeRelationshipFiltersPoc do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tags) do
      add :type, :text, null: false, default: "topic"
    end
  end

  def down do
    alter table(:tags) do
      remove :type
    end
  end
end
